Ackley Homestay/ackley/urls.py
from django.urls import path
from . import views
app_name='ackley'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /ackley/5/results/
    # path('results/', views.ResultsView.as_view(), name='results'),
    # ex: /ackley/5/vote/
    # path('vote/', views.vote, name='vote'),
    path('Contact us/',views.contact,name='contact'),
    path('Photo/',views.photo,name='photo'),
    path('reviews/',views.review,name='reviews'),
    path('booking/',views.online_booking,name='booking'),
]

Ackley Homestay/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ackley.urls'))
]

Ackley Homestay/ackley/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from PIL import Image
from django_resized import ResizedImageField
# Create your models here.

class Contacts(models.Model):       
    Name=models.CharField(max_length=20)
    Email=models.EmailField()
    Phone_Number=models.CharField(max_length=10,default='not given')
    Message=models.TextField(max_length=200)
    date=models.DateTimeField('date added')
    def __str__(self):
        return self.Name

class Bookings(models.Model):
    First_name=models.CharField(max_length=20)
    Last_name=models.CharField(max_length=20)
    Phone_number=models.CharField(max_length=10)
    Email=models.EmailField()
    Date=models.DateField('Date booked')
    Arrival=models.DateField()
    No_of_guests=models.IntegerField()
    No_of_days=models.IntegerField()
    Booking_id=models.CharField(max_length=6)
    def __str__(self):
        return self.First_name+' '+self.Last_name

class Album(models.Model):
    Img=ResizedImageField(size=[294, 225],upload_to='static/images')
    Img_name=models.CharField(max_length=20)
    Img_description=models.TextField()
    def __str__(self) -> str:
        return self.Img_name
    

Ackley Homestay/ackley/views.py
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Bookings, Contacts, Album
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.core.mail import send_mail
import random, string
# def index(request):
#     return HttpResponse('Hello world , You are at the poll index')

# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(requesackley/detail.html', {'question': question})

# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})

# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     context = {'latest_question_list': latest_question_list}
#     return render(request,'polls/index.html',context)


def index(request):
    return render(request, 'ackley/index.html')


def photo(request):
    context = {
        'object': Album.objects.all(),
    }
    return render(request, 'ackley/Photo.html', context)


def review(request):
    return render(request, 'ackley/review.html')


def online_booking(request):

    if request.method == "POST":
        if 'booking' in request.POST:
            if not Bookings.objects.filter(Email=request.POST['email']):
                while True:
                    y = random.randint(1, 6)
                    ls = list(''.join([random.choice(string.ascii_letters) for x in range(y)]) + ''.join([str(random.randint(0, 9)) for x in range(6 - y)]))
                    random.shuffle(ls)
                    bid=''.join(ls)
                    if not Bookings.objects.filter(Booking_id=bid):
                        break                

                q = Bookings(First_name=request.POST.get('fname'),
                             Last_name=request.POST.get('lname'),
                             Phone_number=request.POST.get('number'),
                             Date=timezone.now(),
                             Email=request.POST.get('email'),
                             No_of_guests=request.POST.get('nguests'),
                             No_of_days=request.POST.get('ndays'),
                             Arrival=request.POST.get('arrival'),
                             Booking_id=bid)
                q.save()
                messages.success(
                    request,
                    'Your Booking is Done , you will get a email with booking id'
                )
                send_mail(
                    'Booking Successful',
                    f"{request.POST.get('fname')} \n Your booking is successful for our ackley homestay and we will contact you soon \n Your Booking ID is : {bid}",
                    'Sudhirprakashbahuguna@gmail.com',
                    [request.POST.get('email')],
                    fail_silently=False)
                send_mail(
                    f"{request.POST.get('fname')} Booked",
                    f"{request.POST.get('fname')} {request.POST.get('lname')} \n Booked your ackley homestay on {request.POST.get('arrival')}. \n Phone Number:{request.POST.get('number')} \n Email: {request.POST.get('email')} \n Number of Guests: {request.POST.get('nguests')} \n Number of days they will stay: {request.POST.get('ndays')} \n Their Booking id:{bid}",
                    'Sudhirprakashbahuguna@gmail.com',
                    ['Sudhirprakashbahuguna@gmail.com'],
                    fail_silently=False)
            else:
                messages.warning(request, 'You have already booked')
        elif 'cancel' in request.POST:
            if Bookings.objects.filter(Booking_id=request.POST['bid']):
                canceler = Bookings.objects.get(
                    Booking_id=request.POST['bid'])
                send_mail(
                    'Someone cancelled the booking :/',
                    f'{canceler.First_name} {canceler.Last_name} Canceled his boooking with booking id : {canceler.Booking_id} \n Phone Number: {canceler.Phone_number} \n Email : {canceler.Email} \n reason for cancellation : {request.POST["Message"]}',
                    'sudhirprakashbahuguna@gmail.com',
                    ['sudhirprakashbahuguna@gmail.com'])
                send_mail(
                    'Booking Canceled',
                    f'Your Booking for id {canceler.Booking_id} has Been cancelled successfully','sudhirprakashbahuguna@gmail.com',[canceler.Email]
                )
                canceler.delete()
                messages.success(request,
                                 'Your booking is cancelled Successfully')
            else:
                messages.warning(request, 'You have not Booked yet')

    return render(request, 'ackley/booking.html')


def contact(request):
    if request.method == 'POST':
        q = Contacts(Name=request.POST.get('Name'),
                     Email=request.POST.get('Email'),
                     Message=request.POST.get('Message'),
                     date=timezone.now(),
                     Phone_Number=request.POST.get('Phone'))
        q.save()
        messages.success(request, 'You will be contacted soon')
        send_mail(
            f"{request.POST.get('Name')} tried to contact",
            f"Name: {request.POST['Name']}\n Email:{request.POST['Email']},\n Phone:{request.POST['Phone']}\n Message: {request.POST['Message']}",
            'Sudhirprakashbahuguna@gmail.com',
            ['Sudhirprakashbahuguna@gmail.com'])
    return render(request, 'ackley/contact.html')


# class DetailView(generic.DetailView):
#     model=Question
#     template_name = 'polls/detail.html'

# def vote(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     try:
#         selected_choice = question.choices_set.get(pk=request.POST['choice'])
#     except (KeyError, Choices.DoesNotExist):
#         # Redisplay the question voting form.
#         return render(request, 'ackley/detail.html', {
#             'question': question,
#             'error_message': "You didn't select a choice.",
#         })
#     else:
#         selected_choice.votes += 1
#         selected_choice.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('ackley:results', args=(question.id,)))

Ackley Homestay/ackley/templates/ackley/base.html
<html lang="en">

<head>
    {% block Head %}{% endblock Head %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--favicons-->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <title>Ackley|{% block Title %}{% endblock Title %}
    </title>
    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
          }
          body{
            background-color: rgba(33,37,41,1);
            color:#f3f3f3;
          }

          .form-control{
            background-color: rgba(33,37,41,1);
            color:white
          }
  
        .form-control:focus{
            background-color: rgba(33,37,41,1);
            color:white;

        }
        .card {
          background-color:rgba(33,37,41,1);
        }
        .card-body{
          background-color:rgba(33,37,41,1);
        }

        .btn{
    
          color:white;
          border:1px solid black;
        }
        .navbar{
          background-color:#1c1e1f;

        }

          @media (min-width: 768px) {
            .bd-placeholder-img-lg {
              font-size: 3.5rem;
            }
          }     
          .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
          }
          
          .bi {
            vertical-align: -.125em;
            fill: currentColor;
          }

        </style>


</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Ackley Homestay</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'ackley:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'ackley:booking' %}">Booking</a>
                  </li>
                    {% comment %} <li class="nav-item">
                        <a class="nav-link" href="{% url 'ackley:reviews' %}">Reviews</a>
                    </li> {% endcomment %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ackley:photo' %}">Photos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ackley:contact' %}">Contact Us</a>
                    </li>
                    {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li> {% endcomment %}
                </ul>

            </div>
        </div>
    </nav>
    
    {% block Body %}{% endblock Body %}
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
        <symbol id="facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </symbol>
        <symbol id="instagram" viewBox="0 0 16 16">
            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </symbol>
        <symbol id="twitter" viewBox="0 0 16 16">
          <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </symbol>
      </svg>

    <div class="b-example-divider bg-dark"></div>
    <div class="container bg-dark">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark">
          <div class="col-md-4 d-flex align-items-center bg-darl">
            <span class="text-muted">&copy; 2021 Ackley Homestay, Inc <br>Contact: +91545344543545 <br> Email: sjahdkahsd@gmail.com <br> Address: Gram SAvli chamba, tehri garhwal, uttarakhand</span>
          </div>
      
          <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
            <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
          </ul>
        </footer>
      </div>
  

    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

</body>

</html>

Ackley Homestay/ackley/templates/ackley/booking.html
{% extends 'ackley/base.html' %}
{% block Title %}Booking{% endblock Title %}
{% block Head %}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<style>
    #cancel_booking {
        width: 694px;
        max-width: 100%;
        border: 2px solid #513e00;
    }
    #book{
        border:2px solid #513e00;
    }
</style>

{% endblock Head %}

{% block Body %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{message}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
<br>
<br>
<!-- contact form -->


<div class="col-md-6 wow animated mt-20 fadeInRight" data-wow-delay=".2s" id="book">
    <h1 class="display-4 font-italic">Book Ackley Homestay</h1>
    <p class="lead my-3">You can start booking From Below</p>
    <br>
    <form action="{% url 'ackley:booking' %}" class="shake mt-20" role="form" method="post" id="contactForm"
        name="contact-form" data-toggle="validator">
        {% csrf_token %}
        <!--First Name -->
        <div class="form-group label-floating">
            <label class="control-label" for="name">First Name</label>
            <input class="form-control" id="name" type="text" name="fname" required
                data-error="Please enter your First name">
            <div class="help-block with-errors"></div>
        </div>
        <!--Last Name -->
        <div class="form-group label-floating">
            <label class="control-label" for="name">Last Name</label>
            <input class="form-control" id="name" type="text" name="lname" required
                data-error="Please enter your Last name">
            <div class="help-block with-errors"></div>
        </div>
        <!-- email -->
        <div class="form-group label-floating">
            <label class="control-label" for="email">Email</label>
            <input class="form-control" id="email" type="email" name="email" required
                data-error="Please enter your Email">
            <div class="help-block with-errors"></div>
        </div>
        <!-- Phone Number-->
        <div class="form-group label-floating">
            <label class="control-label">Phone Number</label>
            <input class="form-control" id="msg_subject" type="text" name="number" required
                data-error="Please enter your Phone number">
            <div class="help-block with-errors"></div>
        </div>
        <!--Arrival Date-->
        <div class="form-group label-floating">
            <label class="control-label">Arrival Date</label>
            <input class="form-control" id="msg_subject" type="date" name="arrival" required
                data-error="Please enter your date of Arrival">
            <div class="help-block with-errors"></div>
        </div>
        <!--No of Guests-->
        <div class="form-group label-floating">
            <label class="control-label">No of Guests</label>
            <input class="form-control" id="msg_subject" type="number" name="nguests" required
                data-error="Please enter the number of Guests ">
            <div class="help-block with-errors"></div>
        </div>
        <!--No of days-->
        <div class="form-group label-floating">
            <label class="control-label">No of days you will stay</label>
            <input class="form-control" id="msg_subject" type="number" name="ndays" required
                data-error="Please enter number of days you will stay">
            <div class="help-block with-errors"></div>
        </div>
        <!-- Message -->
        <div class="form-group label-floating">
            <label for="message" class="control-label">Write additional detail about Your booking</label>
            <textarea class="form-control" rows="3" id="message" name="Message" required
                data-error="Describe about your booking"></textarea>
            <div class="help-block with-errors"></div>
        </div>
        <!-- Form Submit -->
        <div class="form-submit mt-5">
            <button class="btn btn-primary" type="submit" name="booking"><i
                    class="material-icons mdi mdi-message-outline"></i>Book Now</button>
            <div id="msgSubmit" class="h3 text-center hidden"></div>
            <div class="clearfix"></div>
        </div>
    </form>
</div>



<div class="b-example-divider bg-dark"></div>
<div class="jumbotron p-1 p-md-5 text-white rounded bg-dark" id="cancel_booking">
    <div class="col-md-9 px-0">
        <h1 class="display-4 font-italic">Cancellation</h1>
        <p class="lead my-3">You can cancel your booking From Below</p>
        <form action="{% url 'ackley:booking' %}" class="shake mt-20" role="form" method="post" id="contactForm"
            name="contact-form" data-toggle="validator">
            {% csrf_token %}
            <div class="form-group label-floating">
                <label class="control-label" for="name">Booking ID</label>
                <input class="form-control" id="name" type="text" name="bid" required
                    data-error="Please enter your First name">
                <div class="help-block with-errors"></div>
            </div>
            <div class="form-group label-floating">
                <label for="message" class="control-label">Reason of your Cancellation</label>
                <textarea class="form-control" rows="3" id="message" name="Message" required
                    data-error="Describe about your booking"></textarea>
                <div class="help-block with-errors"></div>
            </div>
            <div class="form-submit mt-5">
                <button class="btn btn-Danger" type="submit" name="cancel"><i
                        class="material-icons mdi mdi-message-outline"></i>Cancel</button>
                <div id="msgSubmit" class="h3 text-center hidden"></div>
                <div class="clearfix"></div>
            </div>
    </div>

</div>

{% endblock Body %}

Ackley Homestay/ackley/templates/ackley/index.html
{% extends 'ackley/base.html' %}
{% block Title %}Home{% endblock Title %}
{% block Body %}
{% load static %}
<div class="container-fluid mt-0 pt-0 px-0" style='border:2px groove grey'>
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
        aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
        aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static 'images/Ackley2.jpg' %}" class="img-fluid d-block w-100 h-75" alt="Ackley">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/Ackley1.jpg' %}" class="img-fluid d-block w-100 h-75" alt="Ackley">
      </div>
      <div class="carousel-item">
        <img src="{% static 'images/Ackley3.jpg' %}" class="img-fluid d-block w-100 h-75 " alt="Ackley">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>
<div class="b-example-divider bg-dark"></div>
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0">
    <h1 class="display-4 font-italic">Ackley HomeStay</h1>
    <p class="lead my-3">Our HomeStay is Designed for you to experience the beauty of mountains and hills in land of
      Uttarakhand, Situated in tehri district in a place village called Shavli.</p>
  </div>

</div>
<div class="b-example-divider bg-dark"></div>
<div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
  <div class="col-md-6 px-0" style="margin:auto; border-right:2px solid white; border-radius:10px;">
    <h1 class="display-4 font-italic" style="margin-left:20%;">Book Now</h1>

    <p class="lead my-3 px-3">Book your visit from our booking page in just simple and easy steps from our booking page.</p>
    <div class='btn btn-primary' style="margin-left:30%; margin-top:5px">
        <a href={% url 'ackley:booking' %} style="text-decoration:none; color:white;">Book Now</a>
    </div>  
  </div>
</div>
<div class="b-example-divider bg-dark"></div>

  
{% comment %}   
<div class="embed-responsive embed-responsive-16by9">
  <iframe class="embed-responsive-item w-75 h-100 mx-50" src="{% static 'Naruto ship-54.mp4' %}"
    allowfullscreen></iframe>
</div> {% endcomment %}


{% endblock Body %}%}

Ackley Homestay/ackley/templates/ackley/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choices_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'ackley:detail' question.id %}">Vote again?</a>